version: '3'
services:
  service_discovery:
    container_name: service-discovery
    image: eugencic/lab1-web-proxy-service_discovery:latest
    ports:
      - "9090:9090"
    networks:
      - mynetwork

  traffic-analytics-database:
    container_name: traffic-analytics-database
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 397777
      POSTGRES_DB: traffic-analytics-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 15s
      retries: 5
    networks:
      - mynetwork

  traffic-regulation-database:
    container_name: traffic-regulation-database
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: 397777
      POSTGRES_DB: traffic-regulation-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 15s
      retries: 5
    networks:
      - mynetwork

  traffic-analytics-service-1:
    container_name: traffic-analytics-service-1
    image: eugencic/lab1-web-proxy-traffic-analytics-service-1:latest
    ports:
      - "7071:7071"
    restart: always
    depends_on:
      service_discovery:
        condition: service_started
      traffic-analytics-database:
        condition: service_healthy
    networks:
      - mynetwork

  traffic-analytics-service-2:
    container_name: traffic-analytics-service-2
    image: eugencic/lab1-web-proxy-traffic-analytics-service-2:latest
    ports:
      - "7072:7072"
    restart: always
    depends_on:
      service_discovery:
        condition: service_started
      traffic-analytics-database:
        condition: service_healthy
    networks:
      - mynetwork

  traffic-analytics-service-3:
    container_name: traffic-analytics-service-3
    image: eugencic/lab1-web-proxy-traffic-analytics-service-3:latest
    ports:
      - "7073:7073"
    restart: always
    depends_on:
      service_discovery:
        condition: service_started
      traffic-analytics-database:
        condition: service_healthy
    networks:
      - mynetwork

  traffic-regulation-service-1:
    container_name: traffic-regulation-service-1
    image: eugencic/lab1-web-proxy-traffic-regulation-service-1:latest
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      service_discovery:
        condition: service_started
      traffic-regulation-database:
        condition: service_healthy
    networks:
      - mynetwork

  traffic-regulation-service-2:
    container_name: traffic-regulation-service-2
    image: eugencic/lab1-web-proxy-traffic-regulation-service-2:latest
    ports:
      - "8082:8082"
    restart: always
    depends_on:
      service_discovery:
        condition: service_started
      traffic-regulation-database:
        condition: service_healthy
    networks:
      - mynetwork

  traffic-regulation-service-3:
    container_name: traffic-regulation-service-3
    image: eugencic/lab1-web-proxy-traffic-regulation-service-3:latest
    ports:
      - "8083:8083"
    restart: always
    depends_on:
      service_discovery:
        condition: service_started
      traffic-regulation-database:
        condition: service_healthy
    networks:
      - mynetwork

  traffic-analytics-load-balancer:
    container_name: traffic-analytics-load-balancer
    image: eugencic/lab1-web-proxy-traffic-analytics-load-balancer:latest
    ports:
      - "7000:7000"
    restart: always
    depends_on:
      service_discovery:
        condition: service_started
      traffic-analytics-service-1:
        condition: service_started
      traffic-analytics-service-2:
        condition: service_started
      traffic-analytics-service-3:
        condition: service_started
    networks:
      - mynetwork

  traffic-regulation-load-balancer:
    container_name: traffic-regulation-load-balancer
    image: eugencic/lab1-web-proxy-traffic-regulation-load-balancer:latest
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      service_discovery:
        condition: service_started
      traffic-regulation-service-1:
        condition: service_started
      traffic-regulation-service-2:
        condition: service_started
      traffic-regulation-service-3:
        condition: service_started
    networks:
      - mynetwork

  gateway:
    container_name: gateway
    image: eugencic/lab1-web-proxy-gateway:latest
    ports:
      - "6060:6060"
    restart: always
    depends_on:
      service_discovery:
        condition: service_started
      traffic-analytics-load-balancer:
        condition: service_started
      traffic-regulation-load-balancer:
        condition: service_started
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
