# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: traffic.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtraffic.proto\x12\x04main\"\x84\x01\n\x0bTrafficData\x12\x17\n\x0fintersection_id\x18\x01 \x01(\x05\x12\x17\n\x0fsignal_status_1\x18\x02 \x01(\x05\x12\x15\n\rvehicle_count\x18\x03 \x01(\x05\x12\x10\n\x08incident\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x05 \x01(\t\x12\x0c\n\x04time\x18\x06 \x01(\t\"-\n\x1aTrafficDataReceiveResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2U\n\x0fTrafficAnalyzer\x12\x42\n\x0bReceiveData\x12\x11.main.TrafficData\x1a .main.TrafficDataReceiveResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'traffic_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRAFFICDATA']._serialized_start=24
  _globals['_TRAFFICDATA']._serialized_end=156
  _globals['_TRAFFICDATARECEIVERESPONSE']._serialized_start=158
  _globals['_TRAFFICDATARECEIVERESPONSE']._serialized_end=203
  _globals['_TRAFFICANALYZER']._serialized_start=205
  _globals['_TRAFFICANALYZER']._serialized_end=290
# @@protoc_insertion_point(module_scope)
