# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import traffic_pb2 as traffic__pb2


class TrafficAnalyzerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReceiveData = channel.unary_unary(
                '/main.TrafficAnalyzer/ReceiveData',
                request_serializer=traffic__pb2.TrafficData.SerializeToString,
                response_deserializer=traffic__pb2.TrafficDataReceiveResponse.FromString,
                )


class TrafficAnalyzerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReceiveData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrafficAnalyzerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReceiveData': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveData,
                    request_deserializer=traffic__pb2.TrafficData.FromString,
                    response_serializer=traffic__pb2.TrafficDataReceiveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'main.TrafficAnalyzer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TrafficAnalyzer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReceiveData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.TrafficAnalyzer/ReceiveData',
            traffic__pb2.TrafficData.SerializeToString,
            traffic__pb2.TrafficDataReceiveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
